Improve APIs of image io to support passing html id and element
huningxin/opencv pull request #164
Opened 2017-08-04 08:28 UTC by pancx

Support passing canvas id or element and img id or element to cv.imread.
Support passing canvas element or id to cv.imshow.
Support passing video element or id to cv.VideoCapture.

2017-08-04 08:28 UTC, pancx commented
@huningxin  Please have a look.

2017-08-04 09:08 UTC, huningxin requested changes

2017-08-04 09:08 UTC, huningxin commented on modules/js/src/helpers.js
> +    var img = null;
"canvasID" name now seems a bit confusing. Please use some general names.

2017-08-04 09:08 UTC, huningxin commented on modules/js/src/helpers.js
> +    else {
put the else to one line above, like
```
} else {
```

2017-08-04 09:08 UTC, huningxin commented on modules/js/src/helpers.js
> +    ctx = canvas.getContext("2d");
If input is an image, `ctx` is already gotten.

2017-08-07 03:08 UTC, pancx commented
@huningxin Updated. Please have a look.

2017-08-07 03:09 UTC, huningxin approved these changes

2017-08-07 03:09 UTC, huningxin commented
Looks good. Thanks!

2017-08-07 03:09 UTC, merged