[opencv.js doc] add doc for optimization and perf test
huningxin/opencv pull request #292
Opened 2019-08-20 06:18 UTC by Wenzhao-Xiang

fix #279 

### This pullrequest changes
Add doc for how to enable opencv.js optimization and run perf test.

@huningxin @terfendail  PTAL, Thanks!

2019-08-20 06:46 UTC, huningxin requested changes
Finish 1st round of review. Please take a look at comments.

2019-08-20 06:46 UTC, huningxin commented on doc/js_tutorials/js_setup/js_setup/js_setup.markdown
> +    And the failed cases will be print on the console.
And the failed cases will be logged in the JavaScript debug console.

2019-08-20 06:46 UTC, huningxin commented on doc/js_tutorials/js_setup/js_setup/js_setup.markdown
> +    To build wasm intrinsics tests, append `--build_wasm_intrin_test` option.
Move this sentence after following example as it is only useful for development flow.

2019-08-20 06:46 UTC, huningxin commented on doc/js_tutorials/js_setup/js_setup/js_setup.markdown
> +    python ./platforms/js/build_js.py build_js --build_wasm --simd --build_wasm_intrin_test
remove `--build_wasm_intrin_test`

2019-08-20 06:46 UTC, huningxin commented on doc/js_tutorials/js_setup/js_setup/js_setup.markdown
> +-#  [optional] To build `opencv.js` with wasm simd optimization, append `--simd` option.
Need to mention the simd optimization is experimental as wasm simd is still in development.

2019-08-20 06:46 UTC, huningxin commented on doc/js_tutorials/js_setup/js_setup/js_setup.markdown
> +    Now only emscripten LLVM upstream backend support wasm simd, so you need to setup upstream backend environment with the following command first:
"support" -> "supports", it's better to have a link to https://emscripten.org/docs/porting/simd.html

2019-08-20 06:46 UTC, huningxin commented on doc/js_tutorials/js_setup/js_setup/js_setup.markdown
> +    You should build wasm version of `opencv.js` if you want to enable this optimization.
need to mention the threads optimization only works in browser, not in node.js

2019-08-20 06:46 UTC, huningxin commented on doc/js_tutorials/js_setup/js_setup/js_setup.markdown
> +    node threshold.js --test_param_filter="(1920x1080, CV_8UC1, THRESH_BINARY))"
one more ")" at the end.

2019-08-20 06:46 UTC, huningxin commented on doc/js_tutorials/js_setup/js_setup/js_setup.markdown
> +    node threshold.js --test_param_filter="(1920x1080, CV_8UC1, THRESH_BINARY))"
Will the filename be "perf_threshold.js"?

2019-08-20 12:02 UTC, huningxin reviewed
Finish 2nd review. Please take a look at the comments.

2019-08-20 12:02 UTC, huningxin commented on doc/js_tutorials/js_setup/js_setup/js_setup.markdown
> +    You should build wasm version of `opencv.js` if you want to enable this optimization. And the threads optimization only works in browser, not in node.js. You should enable the `WebAssembly thread
Please provide a link that tells how to enable `WebAssembly threads support`, e.g. in chrome.

2019-08-20 12:02 UTC, huningxin commented on doc/js_tutorials/js_setup/js_setup/js_setup.markdown
> +    You should build wasm version of `opencv.js` if you want to enable this optimization. And you should enable the `WebAssembly SIMD support` feature first.
Please state that the `WebAssembly SIMD support` is in web browser.

2019-08-21 03:06 UTC, Wenzhao-Xiang commented
@huningxin updated it.

2019-08-21 05:15 UTC, huningxin commented
Looks good. Merge it so you can work on #295

2019-08-21 05:15 UTC, merged